title: Αρχείο Πανελλήνιου Διαγωνισμού Πληροφορικής
description: Site για τη συλλογή εκφωνήσεων, testcases, λύσεων και κωδίκων για τους Πανελλήνιους Διαγωνισμούς Πληροφορικής (ΠΔΠ). 
timezone: Europe/Athens
permalink: /:title
highlighter: rouge
gems:
  - jekyll-redirect-from

markdown: kramdown
kramdown:
  input: GFM

highlighter: rouge

collections_dir: contests

collections:
  25-PDP:
    output: true
    permalink: /:collection/:name
  26-PDP:
    output: true
    permalink: /:collection/:name
  27-PDP:
    output: true
    permalink: /:collection/:name
  28-PDP:
    output: true
    permalink: /:collection/:name
  29-PDP:
    output: true
    permalink: /:collection/:name
  30-PDP:
    output: true
    permalink: /:collection/:name
  31-PDP:
    output: true
    permalink: /:collection/:name
  32-PDP:
    output: true
    permalink: /:collection/:name
    
defaults:
  - scope:
      path: ""
      type: "25-PDP"
    values:
      contest: "25ος ΠΔΠ"
      contest_url: "25-PDP"
  - scope:
      path: ""
      type: "26-PDP"
    values:
      contest: "26ος ΠΔΠ"
      contest_url: "26-PDP"
  - scope:
      path: ""
      type: "27-PDP"
    values:
      contest: "27ος ΠΔΠ"
      contest_url: "27-PDP"
  - scope:
      path: ""
      type: "28-PDP"
    values:
      contest: "28ος ΠΔΠ"
      contest_url: "28-PDP"
  - scope:
      path: ""
      type: "29-PDP"
    values:
      contest: "29ος ΠΔΠ"
      contest_url: "29-PDP"
  - scope:
      path: ""
      type: "30-PDP"
    values:
      contest: "30ος ΠΔΠ"
      contest_url: "30-PDP"
  - scope:
      path: ""
      type: "31-PDP"
    values:
      contest: "31ος ΠΔΠ"
      contest_url: "31-PDP"
  - scope:
      path: ""
      type: "32-PDP"
    values:
      contest: "32ος ΠΔΠ"
      contest_url: "32-PDP"
